---
engines:
  pylint:
    enabled: false
exclude_paths:
  - 'assets/css/jquery-ui/**'
  - 'assets/js/lib/**'
  - 'tardis/apps/push_to/static/push-to/bootstrap/**'
  - 'tardis/apps/push_to/static/push-to/typeahead.bundle.js'
  - 'tardis/apps/push_to/static/push-to/angular-typeahead.js'
